### ISSUE TITLE
Support for non-ANSI characters

### ISSUE THREAD

**Issue by d-random-contributor** [Eoinocal/Halite#1]
When torrent has files with non-ANSI characters (outside system charset), Halite is able to download the files correctly, but after restart writes to log "Resume data generation failed", displays torrent progress 0% and starts downloading it again. Also "Files" tab is empty.

**Comment by Eoinocal** [comment]
Hi,

Thanks for the report. There is a bug in the files tab unrelated to this
problem. As for these torrents in particular, I'll look into it.

Thanks again,
Eoin

**Comment by Eoinocal** [comment]
Fixed in 4fae63cefc266dcf5222d20d29be0694a020f649

**Comment by d-random-contributor** [comment]
Thanks,

``` cpp
path resume_file = (hal::app().get_working_directory()/L"resume" / (t_i.name_ + L".fastresume")).wstring();
```

As I understand, conversion to string is not needed here: you assign to `path` anyway.

**Comment by Eoinocal** [comment]
HI, thank's yes, that's a redundant and inefficient conversion, at one
point in the path resume_file was probably a wstring.

As an explanation,the  libtorrent API has change a lot over the years, file
paths have gone through at least 3 changes. The last Halite update came
after a 2ish year gap, so it required a lot of refactoring and frankly I
plain forgot to test unicode paths properly after changing the Halite code
to interface with the newer libtorrent API. I think it is fully working
now, but I'm not too surprised a few redundant conversions remain, I want
to catch them all, but at least they don't seem to lose any Unicode data.

BTW, I'm not blaming libtorrent, it was always a library in development so
API changes were inevitable and even welcome.
