### ISSUE TITLE
Not sure if these things are translateable

### ISSUE THREAD

**Issue by maxdeepfield** [Eoinocal/Halite#12]
![image](https://cloud.githubusercontent.com/assets/1029366/8822709/1582e898-3070-11e5-86b9-dd0e5f19269c.png)

**Comment by Eoinocal** [comment]
There were some internal debugging messages which aren't meant to be shown to users, and so aren't translatable. In the next release they will be properly hidden. See a8d968089ba7c1034f0751e202d619ecd3917a33
