### ISSUE TITLE
Files remain open after removing torrent

### ISSUE THREAD

**Issue by d-random-contributor** [Eoinocal/Halite#19]
If a seeding torrent is removed without stopping it, torrent files remain open and can't be deleted from disk. They also (probably) reopen after halite restart. To close files one should stop torrent before removing it.

**Comment by Barough** [comment]
I can verify this also with the latest release of Halite

**Comment by Eoinocal** [comment]
This should be fixed in 8c4dbce5e72a4bc9a6f0f94f57a873a37f7cdef8. If it's not then please reopen this ticket. Thanks.
