### ISSUE TITLE
Permanent full allocation

### ISSUE THREAD

**Issue by redzimskidev** [Eoinocal/Halite#2]
My problem is, I'm downloading a lot of ISO files and Windows' native ISO mounting feature doesn't work with sparsed files. I chose Halite because it allowed me to choose full or compact allocation, but it would be great to choose one of those permanently in settings, not for each particular download, especially that there's not much to be done about it when the download is already started. I created an account on github just to contact you since I found no other way to contact on your website.

**Comment by Eoinocal** [comment]
Hi, That's not a bad idea. I don't have a huge amount of time these days,
but I will add the feature soon.

Thanks.

**Comment by Eoinocal** [comment]
Added in f1669d0ee47e6966dd2df0c81d720be29f08d70a
