### ISSUE TITLE
"Play" button do not resume download or seeding after pause

### ISSUE THREAD

**Issue by maxdeepfield** [Eoinocal/Halite#20]
I think here is a bug in version 0.4.0.2 on Windows 10.
When pause torrent it is impossible to resume it using toolbar button.
Only works on right click torrent and click "Resume".

**Comment by maxdeepfield** [comment]
This also accurs on 0.4.0.1

**Comment by mrplumber** [comment]
Hi,
Using Halite v 0.4.0.3 on Windows 8.1 Enterprise x64. I can confirm that the Play button in the toolbar does seemingly nothing.

**Comment by SYCrash** [comment]
Windows 8.1 Pro user reporting in. 
the Play button does not work either.

**Comment by Eoinocal** [comment]
See https://github.com/Eoinocal/Halite/issues/21#issuecomment-165906000 for and explanation of the fix.
