### ISSUE TITLE
"Pause" button pauses all torrents when only one selected

### ISSUE THREAD

**Issue by maxdeepfield** [Eoinocal/Halite#21]
"Pause" toolbar button pauses all torrents when only one selected, but this does not happen when no torrent selected.

0.4.0.2
Windows 10

**Comment by maxdeepfield** [comment]
This also accurs on 0.4.0.1

**Comment by Eoinocal** [comment]
The pause and play buttons in the toolbar are a global pause and play unrelated to what torrents are selected. However there was a bug with this functionality which is why you were see sych strange behaviour. Fixed in c7a8f245f23c36c8b6299cdc72156f72b6d07c2d
