### ISSUE TITLE
Statistics per torrent counted in terabytes are not so useful

### ISSUE THREAD

**Issue by maxdeepfield** [Eoinocal/Halite#22]
![image](https://cloud.githubusercontent.com/assets/1029366/9034898/d8ed7554-39db-11e5-8434-45e50f92c6c3.png)

**Comment by Eoinocal** [comment]
Spotted that myself. Should never have made it into the last release. Fixed in 074de2184ae1b2dd5a1c50c4e2bc175421aa3626
