### ISSUE TITLE
Buttons are not visible in Add Torrent dialog

### ISSUE THREAD

**Issue by maxdeepfield** [Eoinocal/Halite#23]
![image](https://cloud.githubusercontent.com/assets/1029366/9110390/fa77ecc4-3c45-11e5-8890-51b9552d70da.png)

They appear when try to rezise window.

**Comment by apexlee** [comment]
Can confirm this happens on Windows 10 as well.

Once you resize the dialog to get the buttons to display, it remembers this and is no longer an issue on the next open of the dialog.

**Comment by Eoinocal** [comment]
Thanks. Fixed in a5ef4622a96494e4b59b06c1932f2332f48c5880.
