### ISSUE TITLE
"Total" column in torrent list shows strange values

### ISSUE THREAD

**Issue by maxdeepfield** [Eoinocal/Halite#26]
![image](https://cloud.githubusercontent.com/assets/1029366/9141314/707277dc-3d40-11e5-8ebe-dac4dad3ca7a.png)

**Comment by apexlee** [comment]
"Total" is supposed to be total filesize of the torrent, but yeah I have the same issue.

**Comment by Eoinocal** [comment]
I believe this was fixed in 074de2184ae1b2dd5a1c50c4e2bc175421aa3626 but if I'm wrong then please reopen the issue and I'll take another look at it. Thanks.
