### ISSUE TITLE
Can't add torrents with a "/" in the name

### ISSUE THREAD

**Issue by karlhe** [Eoinocal/Halite#7]
Windows 8.1, 64-bit Halite.

Haven't tested with other special characters. Tried to add a torrent with a "/" both in torrent filename and the downloaded file's filename. Log message displayed:

```
2015-Jun-14 08:10:11 Info, Invalid torrent (00000000-0000-0000-0000-000000000000) from add_torrent.
```

**Comment by Eoinocal** [comment]
HI Karlhe,

Would you be able to share a torrent file with me which demonstrates this. For a start Windows doesn't allow "/" in filenames at all so I'm having trouble reproducing the error. If you can send me a torrent with the error I'll try and fix it.

Thanks,

**Comment by karlhe** [comment]
Upon further inspection it's actually ⁄  which is probably some way to get around the mentioned problem. Apologies, but I'm not really comfortable posting the actual torrent info here.

**Comment by Eoinocal** [comment]
The slash  ⁄  is actually a unicode character and a bug related to unicode
got into the last release. That bug has been fixed and so should hopefully
fix your issue too. The next release with this fix is very close, I'm just
finalising it.
